@src_HostAddress = http://localhost:5230

POST {{src_HostAddress}}
Accept: application/json

{
  "message": "Hello, World!"
}

###

POST {{src_HostAddress}}/header
Accept: application/json

{
  "message": "Hello, World!"
}

###

POST {{src_HostAddress}}/body
Accept: application/json

{
  "message": "Hello, World!"
}
